"""
Converte os CSVs exportados do F1.mdb (Access) para o formato das tabelas
novas no Supabase (schema f1), preservando os IDs originais (as tabelas
foram criadas com "generated BY DEFAULT as identity", o que permite inserir
IDs explícitos).

Como gerar os CSVs de origem (no Windows, com mdbtools ou o próprio Access):
  mdb-export F1.mdb Tb_Ano       > raw/Tb_Ano.csv
  mdb-export F1.mdb TB_TOTAIS    > raw/TB_TOTAIS.csv
  mdb-export F1.mdb TB_PONTUACAO > raw/TB_PONTUACAO.csv
  mdb-export F1.mdb TB_PONTUACAO_SPRINT > raw/TB_PONTUACAO_SPRINT.csv
  mdb-export F1.mdb Tb_Prova     > raw/Tb_Prova.csv
  mdb-export F1.mdb Tb_piloto    > raw/Tb_piloto.csv
  mdb-export F1.mdb Tb_equipe    > raw/Tb_equipe.csv
  mdb-export F1.mdb Tb_Time      > raw/Tb_Time.csv

Uso:
  python3 transform_access_export.py <pasta_raw> <pasta_saida>

Depois, importe os CSVs de saída no Supabase (Table editor > Insert > Import
data from CSV) NESTA ORDEM, respeitando as chaves estrangeiras:
  1. tb_ano
  2. tb_totais, tb_pontuacao, tb_pontuacao_sprint, tb_prova, tb_piloto, tb_equipe
  3. tb_time  (depende de tb_equipe e tb_piloto já estarem carregadas)
"""
import sys
import pandas as pd
from pathlib import Path


def bool_sn(series: pd.Series) -> pd.Series:
    return series.astype(str).str.strip().str.upper().eq('S')


def tipo_carreira(series: pd.Series) -> pd.Series:
    # 'Piloto' -> 'PILOTO' / 'Equipe' -> 'EQUIPE'
    return series.astype(str).str.strip().str.upper()


def delphi_tcolor_to_hex(value: int) -> str:
    """TColor do Delphi é armazenado como 0x00BBGGRR (inteiro decimal)."""
    value = int(value)
    b = (value >> 16) & 0xFF
    g = (value >> 8) & 0xFF
    r = value & 0xFF
    return f'#{r:02X}{g:02X}{b:02X}'


def main(raw_dir: str, out_dir: str):
    raw = Path(raw_dir)
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    # tb_ano ------------------------------------------------------------
    ano = pd.read_csv(raw / 'Tb_Ano.csv')
    ano_out = pd.DataFrame({'id': ano['Id'], 'ano': ano['Ano']})
    ano_out.to_csv(out / 'tb_ano.csv', index=False)

    # tb_totais -----------------------------------------------------------
    tot = pd.read_csv(raw / 'TB_TOTAIS.csv')
    tot_out = pd.DataFrame({
        'id': tot['ID_TOTAL'],
        'ano_jogo': tot['ANO_JOGO'],
        'equipes': tot['EQUIPES'],
        'provas': tot['PROVAS'],
        # 'pilotos' é coluna gerada (equipes*2) — não exportar
        'ponto_volta': bool_sn(tot['PONTO_VOLTA'])
    })
    tot_out.to_csv(out / 'tb_totais.csv', index=False)

    # tb_pontuacao / tb_pontuacao_sprint -----------------------------------
    for src, dst in [('TB_PONTUACAO.csv', 'tb_pontuacao.csv'),
                      ('TB_PONTUACAO_SPRINT.csv', 'tb_pontuacao_sprint.csv')]:
        p = pd.read_csv(raw / src)
        p_out = pd.DataFrame({
            'id': p['ID_PONTO'],
            'ano_jogo': p['ANO_JOGO'],
            'posicao': p['POSICAO'],
            'pontos': p['PONTOS']
        })
        p_out.to_csv(out / dst, index=False)

    # tb_prova --------------------------------------------------------------
    prova = pd.read_csv(raw / 'Tb_Prova.csv')
    prova_out = pd.DataFrame({
        'id': prova['Id_Prova'],
        'ano_jogo': prova['Ano_Jogo'],
        'ordem': prova.groupby('Ano_Jogo').cumcount() + 1,
        'nome_prova': prova['Nome_Prova'],
        'abreviacao_prova': prova['Abreviacao_Prova'],
        'sprint': bool_sn(prova['Sprint']),
        'bandeira': ''  # não existia no Access; preencher manualmente depois
    })
    prova_out.to_csv(out / 'tb_prova.csv', index=False)

    # tb_piloto ---------------------------------------------------------------
    piloto = pd.read_csv(raw / 'Tb_piloto.csv')
    piloto_out = pd.DataFrame({
        'id': piloto['Id_Piloto'],
        'ano_jogo': piloto['Ano_Jogo'],
        'nome_piloto': piloto['Nome_Piloto'],
        'abreviacao_piloto': piloto['Abreviacao_Piloto'],
        'aposentado': bool_sn(piloto['Aposentado']),
        'tipo_carreira': tipo_carreira(piloto['Tipo_Carreira']),
        'pais': ''  # não existia no Access; preencher manualmente depois
    })
    piloto_out.to_csv(out / 'tb_piloto.csv', index=False)

    # tb_equipe -----------------------------------------------------------
    equipe = pd.read_csv(raw / 'Tb_equipe.csv')
    equipe_out = pd.DataFrame({
        'id': equipe['Id_Equipe'],
        'ano_jogo': equipe['Ano_Jogo'],
        'nome_equipe': equipe['Nome_Equipe'],
        'cor_equipe': equipe['Cor_Equipe'].apply(delphi_tcolor_to_hex),
        'tipo_carreira': tipo_carreira(equipe['Tipo_Carreira'])
    })
    equipe_out.to_csv(out / 'tb_equipe.csv', index=False)

    # tb_time ---------------------------------------------------------------
    time_ = pd.read_csv(raw / 'Tb_Time.csv')
    time_out = pd.DataFrame({
        'id': time_['Id_Time'],
        'ano_jogo': time_['Ano_Jogo'],
        'temporada': time_['Temporada'],
        'id_equipe': time_['Id_Equipe'],
        'id_piloto': time_['Id_Piloto'],
        'status_piloto': time_['Status_Piloto'],
        'tipo_carreira': tipo_carreira(time_['Tipo_Carreira'])
    })
    time_out.to_csv(out / 'tb_time.csv', index=False)

    print(f'CSVs gerados em: {out.resolve()}')


if __name__ == '__main__':
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)
    main(sys.argv[1], sys.argv[2])
