-- ============================================================================
-- F1 Manager — schema inicial (Supabase / Postgres)
-- Espelha o banco Access (F1.mdb) do sistema Delphi, mantendo as mesmas
-- "chaves de negócio": ANO_JOGO (ano de lançamento do jogo), TEMPORADA
-- (1 a 10, dentro do ano) e TIPO_CARREIRA ('PILOTO' ou 'EQUIPE' — o modo
-- de carreira escolhido no jogo).
--
-- Diferente do Access, aqui usamos "identity" (serial) para todas as PKs
-- e chaves estrangeiras reais entre tabelas, mas os nomes de coluna do
-- domínio (ano_jogo, temporada, tipo_carreira, id_piloto, id_equipe...)
-- foram mantidos para facilitar o mapeamento mental com o Delphi.
-- ============================================================================

create schema if not exists f1;

-- ----------------------------------------------------------------------------
-- tb_ano — anos de jogo cadastrados (ex.: 2023, 2024, 2025...)
-- Equivalente a Tb_Ano no Access.
-- ----------------------------------------------------------------------------
create table if not exists f1.tb_ano (
  id         bigint generated by default as identity primary key,
  ano        integer not null unique,
  created_at timestamptz not null default now()
);

comment on table f1.tb_ano is 'Anos de jogo cadastrados (ano_jogo). Equivale a Tb_Ano no Access.';

-- ----------------------------------------------------------------------------
-- tb_totais — parâmetros de cada ano de jogo
-- Equivalente a TB_TOTAIS no Access.
-- quantidade de pilotos é sempre equipes * 2 (regra que já existia no Delphi),
-- calculada automaticamente por trigger para não depender do front-end.
-- ----------------------------------------------------------------------------
create table if not exists f1.tb_totais (
  id           bigint generated by default as identity primary key,
  ano_jogo     integer not null references f1.tb_ano(ano) on update cascade,
  equipes      integer not null check (equipes > 0),
  provas       integer not null check (provas > 0),
  pilotos      integer generated always as (equipes * 2) stored,
  ponto_volta  boolean not null default false, -- ponto extra p/ volta mais rápida
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (ano_jogo)
);

comment on table f1.tb_totais is 'Parâmetros do ano (qtd. equipes/provas/pilotos, ponto extra de volta). Equivale a TB_TOTAIS.';

-- ----------------------------------------------------------------------------
-- tb_pontuacao / tb_pontuacao_sprint — tabela de pontos por posição
-- Equivalente a TB_PONTUACAO e TB_PONTUACAO_SPRINT.
-- ----------------------------------------------------------------------------
create table if not exists f1.tb_pontuacao (
  id        bigint generated by default as identity primary key,
  ano_jogo  integer not null references f1.tb_ano(ano) on update cascade,
  posicao   integer not null check (posicao > 0),
  pontos    integer not null check (pontos >= 0),
  unique (ano_jogo, posicao)
);

create table if not exists f1.tb_pontuacao_sprint (
  id        bigint generated by default as identity primary key,
  ano_jogo  integer not null references f1.tb_ano(ano) on update cascade,
  posicao   integer not null check (posicao > 0),
  pontos    integer not null check (pontos >= 0),
  unique (ano_jogo, posicao)
);

comment on table f1.tb_pontuacao is 'Pontos por posição (corrida normal). Equivale a TB_PONTUACAO.';
comment on table f1.tb_pontuacao_sprint is 'Pontos por posição (sprint). Equivale a TB_PONTUACAO_SPRINT.';

-- ----------------------------------------------------------------------------
-- tb_prova — calendário de provas do ano
-- Equivalente a Tb_Prova. Campo bandeira é novo (não existia no Access),
-- pedido para exibir a bandeira do país da prova no grid "Prova a Prova".
-- ----------------------------------------------------------------------------
create table if not exists f1.tb_prova (
  id                bigint generated by default as identity primary key,
  ano_jogo          integer not null references f1.tb_ano(ano) on update cascade,
  ordem             integer not null default 1, -- ordem no calendário
  nome_prova        text not null,
  abreviacao_prova  text not null,
  sprint            boolean not null default false,
  bandeira          text, -- código do país p/ imagem da bandeira (ex.: 'BRA', 'ING', 'ITA')
  created_at        timestamptz not null default now()
);

comment on table f1.tb_prova is 'Calendário de provas do ano. Equivale a Tb_Prova (+ campo bandeira, novo).';

-- ----------------------------------------------------------------------------
-- tb_piloto — pilotos
-- Equivalente a Tb_Piloto. Pilotos aposentados usam ano_jogo = 2000
-- (mesma convenção do sistema atual, usada para os Recordes).
-- Campo pais é novo, para exibir a bandeira do piloto no grid principal.
-- ----------------------------------------------------------------------------
create table if not exists f1.tb_piloto (
  id                  bigint generated by default as identity primary key,
  ano_jogo            integer not null, -- 2000 = piloto aposentado (não referencia tb_ano)
  nome_piloto         text not null,
  abreviacao_piloto   text not null, -- sigla de 3 letras (ex.: NOR, VER)
  aposentado          boolean not null default false,
  tipo_carreira       text not null check (tipo_carreira in ('PILOTO','EQUIPE')),
  pais                text, -- código do país p/ bandeira (ex.: 'ING', 'BRA')
  created_at          timestamptz not null default now()
);

comment on table f1.tb_piloto is 'Pilotos. Equivale a Tb_Piloto (+ campo pais, novo, para bandeira no grid).';

-- ----------------------------------------------------------------------------
-- tb_equipe — equipes/construtores
-- Equivalente a Tb_equipe. Cor guardada como hex (#RRGGBB) em vez do
-- inteiro TColor do Delphi, mais direto para uso na web.
-- ----------------------------------------------------------------------------
create table if not exists f1.tb_equipe (
  id             bigint generated by default as identity primary key,
  ano_jogo       integer not null references f1.tb_ano(ano) on update cascade,
  nome_equipe    text not null,
  cor_equipe     text not null default '#FFFFFF', -- formato #RRGGBB
  tipo_carreira  text not null check (tipo_carreira in ('PILOTO','EQUIPE')),
  created_at     timestamptz not null default now()
);

comment on table f1.tb_equipe is 'Equipes/construtores do ano. Equivale a Tb_equipe.';

-- ----------------------------------------------------------------------------
-- tb_time — escalação (qual piloto corre por qual equipe, em cada temporada)
-- Equivalente a Tb_Time.
-- ----------------------------------------------------------------------------
create table if not exists f1.tb_time (
  id             bigint generated by default as identity primary key,
  ano_jogo       integer not null references f1.tb_ano(ano) on update cascade,
  temporada      integer not null check (temporada between 1 and 10),
  id_equipe      bigint not null references f1.tb_equipe(id) on delete restrict,
  id_piloto      bigint not null references f1.tb_piloto(id) on delete restrict,
  status_piloto  integer not null check (status_piloto in (1,2)), -- 1º ou 2º piloto da equipe
  tipo_carreira  text not null check (tipo_carreira in ('PILOTO','EQUIPE')),
  created_at     timestamptz not null default now(),
  unique (ano_jogo, temporada, id_equipe, status_piloto, tipo_carreira)
);

comment on table f1.tb_time is 'Escalação de pilotos por equipe/temporada. Equivale a Tb_Time.';

-- ----------------------------------------------------------------------------
-- updated_at automático em tb_totais
-- ----------------------------------------------------------------------------
create or replace function f1.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_tb_totais_updated_at on f1.tb_totais;
create trigger trg_tb_totais_updated_at
  before update on f1.tb_totais
  for each row execute function f1.set_updated_at();

-- ----------------------------------------------------------------------------
-- Índices de apoio (consultas sempre filtram por ano_jogo/tipo_carreira)
-- ----------------------------------------------------------------------------
create index if not exists idx_tb_piloto_ano_tipo on f1.tb_piloto (ano_jogo, tipo_carreira);
create index if not exists idx_tb_equipe_ano_tipo on f1.tb_equipe (ano_jogo, tipo_carreira);
create index if not exists idx_tb_time_ano_temp_tipo on f1.tb_time (ano_jogo, temporada, tipo_carreira);
create index if not exists idx_tb_prova_ano on f1.tb_prova (ano_jogo, ordem);

-- ----------------------------------------------------------------------------
-- RLS: por padrão o Supabase habilita RLS quando exposto via API pública.
-- Como este é um app interno de administração, a recomendação inicial é
-- acessar via chave de serviço (service role) a partir do backend do
-- Next.js (Server Actions), sem expor essas tabelas ao cliente anônimo.
-- Caso queira usar a anon key no browser, crie policies específicas aqui.
-- ----------------------------------------------------------------------------
alter table f1.tb_ano              enable row level security;
alter table f1.tb_totais           enable row level security;
alter table f1.tb_pontuacao        enable row level security;
alter table f1.tb_pontuacao_sprint enable row level security;
alter table f1.tb_prova            enable row level security;
alter table f1.tb_piloto           enable row level security;
alter table f1.tb_equipe           enable row level security;
alter table f1.tb_time             enable row level security;

-- Nenhuma policy criada de propósito: sem policy, a anon key não lê/grava
-- nada; o acesso via service role (usado nos Server Actions) ignora RLS.
