-- ============================================================================
-- Parte 2 — Prova a Prova: resultados de cada corrida (posição, pole, volta
-- mais rápida) e, quando a prova tem sprint, o resultado da sprint.
--
-- Diferente do Access (que guardava isso em tabelas largas, com uma coluna
-- Prova1..Prova25 por piloto — Tb_Classificacao, Tb_Pole, Tb_Volta,
-- Tb_Sprint), aqui normalizei para UMA LINHA por (piloto, prova, temporada):
-- é o mesmo dado, só que em formato relacional de verdade — permite juntar
-- com tb_prova/tb_piloto/tb_equipe direto, sem ficar lendo coluna por
-- número de prova. Os pontos de cada corrida e a classificação da
-- temporada são calculados a partir daqui (junto com tb_pontuacao /
-- tb_pontuacao_sprint / tb_totais.ponto_volta), não ficam duplicados em
-- outra tabela.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- tb_resultado — resultado da corrida principal de cada prova.
-- Equivale a Tb_Classificacao (posição) + Tb_Pole (pole) + Tb_Volta (volta
-- mais rápida) do Access, só que em uma linha por piloto/prova.
-- ----------------------------------------------------------------------------
create table if not exists f1.tb_resultado (
  id                 bigint generated by default as identity primary key,
  ano_jogo           integer not null references f1.tb_ano(ano) on update cascade,
  temporada          integer not null check (temporada between 1 and 10),
  id_prova           bigint not null references f1.tb_prova(id) on delete cascade,
  id_piloto          bigint not null references f1.tb_piloto(id) on delete cascade,
  tipo_carreira      text not null check (tipo_carreira in ('PILOTO','EQUIPE')),
  posicao            integer check (posicao > 0), -- null = não terminou / não largou
  pole               boolean not null default false,
  volta_mais_rapida  boolean not null default false,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  unique (ano_jogo, temporada, id_prova, id_piloto, tipo_carreira)
);

comment on table f1.tb_resultado is 'Resultado da corrida por piloto/prova. Equivale a Tb_Classificacao + Tb_Pole + Tb_Volta.';

-- só pode haver um piloto em cada posição de chegada, por prova/temporada
create unique index if not exists uq_tb_resultado_posicao
  on f1.tb_resultado (ano_jogo, temporada, id_prova, tipo_carreira, posicao)
  where posicao is not null;

-- só pode haver uma pole e uma volta mais rápida por prova/temporada
create unique index if not exists uq_tb_resultado_pole
  on f1.tb_resultado (ano_jogo, temporada, id_prova, tipo_carreira)
  where pole;

create unique index if not exists uq_tb_resultado_volta
  on f1.tb_resultado (ano_jogo, temporada, id_prova, tipo_carreira)
  where volta_mais_rapida;

drop trigger if exists trg_tb_resultado_updated_at on f1.tb_resultado;
create trigger trg_tb_resultado_updated_at
  before update on f1.tb_resultado
  for each row execute function f1.set_updated_at();

-- ----------------------------------------------------------------------------
-- tb_resultado_sprint — resultado da corrida sprint (só existe quando
-- tb_prova.sprint = true para aquela prova). Equivale a Tb_Sprint.
-- ----------------------------------------------------------------------------
create table if not exists f1.tb_resultado_sprint (
  id          bigint generated by default as identity primary key,
  ano_jogo    integer not null references f1.tb_ano(ano) on update cascade,
  temporada   integer not null check (temporada between 1 and 10),
  id_prova    bigint not null references f1.tb_prova(id) on delete cascade,
  id_piloto   bigint not null references f1.tb_piloto(id) on delete cascade,
  tipo_carreira text not null check (tipo_carreira in ('PILOTO','EQUIPE')),
  posicao     integer check (posicao > 0),
  created_at  timestamptz not null default now(),
  unique (ano_jogo, temporada, id_prova, id_piloto, tipo_carreira)
);

comment on table f1.tb_resultado_sprint is 'Resultado da sprint por piloto/prova. Equivale a Tb_Sprint.';

create unique index if not exists uq_tb_resultado_sprint_posicao
  on f1.tb_resultado_sprint (ano_jogo, temporada, id_prova, tipo_carreira, posicao)
  where posicao is not null;

create index if not exists idx_tb_resultado_temporada
  on f1.tb_resultado (ano_jogo, temporada, tipo_carreira);
create index if not exists idx_tb_resultado_sprint_temporada
  on f1.tb_resultado_sprint (ano_jogo, temporada, tipo_carreira);

-- ----------------------------------------------------------------------------
-- RLS — mesma decisão do resto do app (app interno, sem login ainda):
-- ver supabase/migrations/0002_policies_anon.sql para o motivo.
-- ----------------------------------------------------------------------------
alter table f1.tb_resultado        enable row level security;
alter table f1.tb_resultado_sprint enable row level security;

drop policy if exists anon_all_tb_resultado on f1.tb_resultado;
create policy anon_all_tb_resultado on f1.tb_resultado for all to anon using (true) with check (true);

drop policy if exists anon_all_tb_resultado_sprint on f1.tb_resultado_sprint;
create policy anon_all_tb_resultado_sprint on f1.tb_resultado_sprint for all to anon using (true) with check (true);

grant select, insert, update, delete on f1.tb_resultado, f1.tb_resultado_sprint to anon;
