-- ============================================================================
-- tb_recorde — valor-base dos recordes (vitórias, poles, voltas mais rápidas,
-- pódios) de cada piloto, gravado manualmente por ano_jogo.
--
-- Convenção (igual à de tb_piloto): o valor gravado aqui para um ano_jogo X
-- é o total ACUMULADO ATÉ O ANO ANTERIOR (X-1). A tela de Recordes (leitura)
-- soma esse valor-base com tudo que já foi disputado nas temporadas do
-- ano_jogo selecionado (tb_resultado), então:
--   - pilotos em atividade: valor-base (até o ano anterior) + resultados do
--     ano_jogo corrente = total sempre atualizado;
--   - pilotos aposentados (ano_jogo = 2000, mesma convenção de tb_piloto):
--     não têm resultados lançados em nenhum ano_jogo real, então o total
--     mostrado é sempre igual ao valor-base — fixo, como deve ser.
--
-- Por isso ano_jogo aqui NÃO referencia tb_ano (mesmo motivo de tb_piloto):
-- precisa aceitar o valor 2000 para os aposentados.
-- ============================================================================

create table if not exists f1.tb_recorde (
  id                   bigint generated by default as identity primary key,
  ano_jogo             integer not null, -- 2000 = valor fixo de piloto aposentado
  tipo_carreira        text not null check (tipo_carreira in ('PILOTO','EQUIPE')),
  id_piloto            bigint not null references f1.tb_piloto(id) on delete cascade,
  vitorias             integer not null default 0 check (vitorias >= 0),
  poles                integer not null default 0 check (poles >= 0),
  voltas_mais_rapidas  integer not null default 0 check (voltas_mais_rapidas >= 0),
  podios               integer not null default 0 check (podios >= 0),
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  unique (ano_jogo, tipo_carreira, id_piloto)
);

comment on table f1.tb_recorde is
  'Valor-base de recordes (até o ano anterior ao ano_jogo). Aposentados usam ano_jogo=2000, valor fixo. Somado com tb_resultado do ano corrente na tela de leitura.';

drop trigger if exists trg_tb_recorde_updated_at on f1.tb_recorde;
create trigger trg_tb_recorde_updated_at
  before update on f1.tb_recorde
  for each row execute function f1.set_updated_at();

create index if not exists idx_tb_recorde_ano_tipo on f1.tb_recorde (ano_jogo, tipo_carreira);

-- RLS: segue o mesmo padrão anon-aberto usado até aqui (ver 0002). A migration
-- 0005_auth.sql substitui isso (e todo o resto do app) por acesso autenticado.
alter table f1.tb_recorde enable row level security;

drop policy if exists anon_all_tb_recorde on f1.tb_recorde;
create policy anon_all_tb_recorde on f1.tb_recorde for all to anon using (true) with check (true);

grant select, insert, update, delete on f1.tb_recorde to anon;
