-- ============================================================================
-- tb_bandeira — catálogo de bandeiras usado no combo de Calendário/Provas e
-- no grid de Classificação Geral, agora gravado no banco em vez de precisar
-- alterar código (src/lib/flags.ts + public/flags/*.png) e fazer novo
-- build/deploy toda vez que surge um GP novo (ex.: uma prova em país que
-- ainda não tinha bandeira cadastrada).
--
-- url_imagem guarda a URL pública completa da imagem (fica assim mais simples
-- pro front-end, que só usa <img src={url_imagem}>). As bandeiras que já
-- existiam antes desta migration (public/flags/*.png, cadastradas em
-- src/lib/flags.ts) são inseridas abaixo apontando pra esse mesmo caminho
-- estático — continuam funcionando sem precisar reenviar os PNGs. Dali em
-- diante, novas bandeiras são cadastradas pela tela "Bandeiras" do app, que
-- faz upload da imagem pro Supabase Storage (bucket "bandeiras") e grava a
-- URL pública gerada aqui.
-- ============================================================================

create table if not exists f1.tb_bandeira (
  id         bigint generated by default as identity primary key,
  codigo     text not null unique,
  nome       text not null,
  url_imagem text not null,
  created_at timestamptz not null default now()
);

comment on table f1.tb_bandeira is 'Catálogo de bandeiras (código + nome + URL da imagem), usado no calendário de provas e no grid de Classificação Geral.';

alter table f1.tb_bandeira enable row level security;

drop policy if exists auth_all_tb_bandeira on f1.tb_bandeira;
create policy auth_all_tb_bandeira on f1.tb_bandeira for all to authenticated using (true) with check (true);

grant usage on schema f1 to authenticated;
grant select, insert, update, delete on f1.tb_bandeira to authenticated;
grant usage, select on all sequences in schema f1 to authenticated;

-- Mantém as bandeiras que já existiam "hardcoded" em src/lib/flags.ts,
-- apontando para os PNGs que já estão em public/flags/ (continuam servidos
-- normalmente pela Vercel — não precisam ser reenviados).
insert into f1.tb_bandeira (codigo, nome, url_imagem) values
  ('ABU', 'Abu Dhabi',                    '/flags/ABU.png'),
  ('AUS', 'Austrália',                    '/flags/AUS.png'),
  ('AUT', 'Áustria',                      '/flags/AUT.png'),
  ('AZE', 'Azerbaijão',                   '/flags/AZE.png'),
  ('BAH', 'Bahrein',                      '/flags/BAH.png'),
  ('BEL', 'Bélgica',                      '/flags/BEL.png'),
  ('BRA', 'Brasil',                       '/flags/BRA.png'),
  ('CAN', 'Canadá',                       '/flags/CAN.png'),
  ('CHI', 'China',                        '/flags/CHI.png'),
  ('ESP', 'Espanha',                      '/flags/ESP.png'),
  ('EUA', 'Estados Unidos',               '/flags/EUA.png'),
  ('FRA', 'França',                       '/flags/FRA.png'),
  ('HOL', 'Holanda',                      '/flags/HOL.png'),
  ('HUN', 'Hungria',                      '/flags/HUN.png'),
  ('IMO', 'Emilia Romagna (Imola)',       '/flags/IMO.png'),
  ('ING', 'Inglaterra',                   '/flags/ING.png'),
  ('ITA', 'Itália',                       '/flags/ITA.png'),
  ('JAP', 'Japão',                        '/flags/JAP.png'),
  ('JID', 'Arábia Saudita (Jidá)',        '/flags/JID.png'),
  ('MEX', 'México',                       '/flags/MEX.png'),
  ('MIA', 'Miami',                        '/flags/MIA.png'),
  ('MON', 'Mônaco',                       '/flags/MON.png'),
  ('POR', 'Portugal',                     '/flags/POR.png'),
  ('QAT', 'Catar',                        '/flags/QAT.png'),
  ('RUS', 'Rússia',                       '/flags/RUS.png'),
  ('SIN', 'Singapura',                    '/flags/SIN.png'),
  ('VEG', 'Las Vegas',                    '/flags/VEG.png')
on conflict (codigo) do nothing;

-- ----------------------------------------------------------------------------
-- Storage: bucket público "bandeiras", onde a tela "Bandeiras" do app faz
-- upload dos PNGs das bandeiras novas. Público porque a imagem é exibida
-- via <img src> puro (sem header de autenticação) nas telas de Calendário
-- e Classificação Geral — mesmo trade-off de exposição que a anon key/URL
-- do projeto já têm hoje (ver comentário em 0002_policies_anon.sql).
-- ----------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('bandeiras', 'bandeiras', true)
on conflict (id) do nothing;

drop policy if exists bandeiras_leitura_publica on storage.objects;
create policy bandeiras_leitura_publica
  on storage.objects for select
  to public
  using (bucket_id = 'bandeiras');

drop policy if exists bandeiras_escrita_autenticado on storage.objects;
create policy bandeiras_escrita_autenticado
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'bandeiras');

drop policy if exists bandeiras_update_autenticado on storage.objects;
create policy bandeiras_update_autenticado
  on storage.objects for update
  to authenticated
  using (bucket_id = 'bandeiras')
  with check (bucket_id = 'bandeiras');

drop policy if exists bandeiras_delete_autenticado on storage.objects;
create policy bandeiras_delete_autenticado
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'bandeiras');
